version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/android:api-28
    steps:
    - checkout

    - run:
        name: Download Dependencies
        command: ./gradlew build --refresh-dependencies
    - run:
        name: Run Tests
        command: ./gradlew --stacktrace runTestInferenceService -DEnvironment=Production
    - run:
            name: Save test results
            command: |
                mkdir -p ~/build/test-output/
                find . -type f -regex ".*/build/test-output/.*html" -exec cp {} ~/build/test-output/ \;
            when: always
    - store_test_results:
            path: ~/test-output
    - store_artifacts:
            path: ~/test-output