version: 2
orbs:
  allure: ayte/allure@0.1.2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/android:api-28
    steps:
    - checkout

    - run:
        name: Download Dependencies
        command: ./gradlew build --refresh-dependencies
    - run:
        name: Run Infernce Tests
        command: ./gradlew --stacktrace runTestInferenceService -DEnvironment=Production



    steps:
      - run:
          name: Save test results
          command: |
            mkdir -p ~/cucumber
            bundle exec cucumber pretty --format json --out ~/cucumber/tests.cucumber
          when: always
      - store_test_results:
          path: ~/cucumber
      - store_artifacts:
          path: ~/cucumber 