version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:9-jdk-sid-node-browsers
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: gradle assemble
            - run: ./gradlew --stacktrace runTestInferenceService -DEnvironment=Production
            - run: gradle run
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs