version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/android:api-28
    steps:
    - checkout

    - run:
        name: Download Dependencies
        command: ./gradlew build --refresh-dependencies
    - run:
        name: Run Tests
        command: ./gradlew --stacktrace runTestInferenceService -DEnvironment=Production

# 