version: 2
orbs:
  allure: ayte/allure@0.1.2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/android:api-28
    steps:
    - checkout

    - run:
        name: Download Dependencies
        command: ./gradlew build --refresh-dependencies
    - run:
        name: Run Tests
        command: ./gradlew --stacktrace runTestInferenceService -DEnvironment=Production
    - run:
            name: Save test results
            command: |
                mkdir -p ~/test-results/junit/
                find . -type f -regex ".*/build/test-results/.html" -exec cp {} ~/test-results/junit/ \;
            when: always
    - store_test_results:
            path: ~/test-results
    - store_artifacts:
            path: ~/test-results/junit